packages/ui/components.json, packages/ui/package.json, packages/ui/src/shad/ui/button.tsx, packages/ui/src/shad/ui/card.tsx, packages/ui/src/shad/ui/input.tsx, packages/ui/src/shad/ui/resizable.tsx, packages/ui/src/shad/ui/scroll-area.tsx, packages/ui/src/shad/ui/select.tsx, packages/ui/src/shad/ui/tabs.tsx, packages/ui/src/shad/ui/toaster.tsx, packages/ui/src/shad/ui/tooltip.tsx, packages/ui/src/shad/ui/use-toast.ts
=> fixes import on new shadcn component

apps/web/app/layout.tsx, packages/ui/package.json, packages/ui/src/Appbar.tsx, packages/ui/src/ModeToggle.tsx, packages/ui/src/shad/ui/dropdown-menu.tsx, yarn.lock
This PR Adds a Light/Dark Mode Using the Next Themes.
Fixes #16 
System Mode
Dark Theme
Light Theme
=> Added Light and Dark Mode Using Next Themes

package-lock.json, package.json, packages/ui/src/pages/Signup.tsx, yarn.lock
=> fix: SVG and Text not rendering properly

packages/ui/src/BlogAppbar.tsx
=> Fixes #22: Added Home button in Appbar

apps/backend/functions/src/routes/tracks.ts, apps/web/screens/Landing.tsx, packages/store/src/atoms/tracks.ts
Fixes #13 
Added a field `hidden` in the `Track` interface which designates a track to be hidden on the front end if this field is set to `true`.
=> Add hidden field in Tracks collection to signify which tracks to show on frontend

packages/ui/src/TrackCard.tsx, packages/ui/src/shad/ui/button.tsx
fixes: UI & Responsiveness of Trackcard on landing page for enhanced readability.
Before 
vs 
After
=> fix: Trackcard UI

packages/ui/src/BlogAppbar.tsx
Bug Fix: Fixed the Navbar being Boned in Lght Mode 
Fixes #36
=> Fixed the Navbar Boned Error in Light Mode

apps/web/screens/Landing.tsx, packages/ui/src/Appbar.tsx, packages/ui/src/BlogAppbar.tsx, packages/ui/src/NotionRenderer.tsx, packages/ui/src/TrackCard.tsx
- Appbar in light/dark mode.
- Blog-Appbar responsiveness.
- Theme toggle button added in blog-view.
- Appbar Appearance on Homescreen (DailyCode visibility in different themes).
- Trackcard shadow in light mode.
=> Fixed Appbar & Trackcard

package-lock.json, packages/ui/src/BlogAppbar.tsx, packages/ui/src/PageToggle.tsx, yarn.lock
=> feat: Added "Jump to" page feature with problem title

packages/ui/src/Appbar.tsx, packages/ui/src/BlogAppbar.tsx
Navbar disappears while scrolling making it hard to navigate. So fixed to the top. Made the changes in both Appbar.tsx and BlogAppbar.tsx
Before
After
=> Fixed the nav bar so it doesn't disappear when scrolling

packages/ui/src/Blog.tsx, packages/ui/src/CodeProblemRenderer.tsx, packages/ui/src/NotionRenderer.tsx, packages/ui/src/hooks/useMountStatus.ts
This pull request resolves the theme flash on tracks page
- Resolved a theme flash on the tracks page during a hard refresh, where a momentary display of the light theme occurred before switching to the dark theme. Also addressed a hydration mismatch in class names during development, caused by the next-themes library.
Flash Error
https://github.com/code100x/daily-code/assets/66407522/a1be0c05-2a21-4bdd-803a-d8c7ae33115b
1. Introduced a custom component mount hook to ensure the client-side component is fully mounted before theme changes, eliminating the flash effect.
2. Resolved hydration mismatch related to class names, specifically caused by the react-notion library.
Thoroughly tested to ensure a seamless theme experience in various scenarios, including normal navigation, hard …
=> Fix : next-themes hydration mismatch and layout shift

apps/web/app/pdf/[...pdfId]/page.tsx, apps/web/components/Print.tsx, packages/ui/src/Blog.tsx, packages/ui/src/LessonView.tsx
Allowed the page to render properly before it can generate the pdf from the page content.
After the changes the pdf is being loaded properly.
=> Fixed code100x#248 the Download PDF action.

packages/ui/src/BlogAppbar.tsx
=> Make BlogAppbar responsive

packages/ui/src/BlogAppbar.tsx
=> Added functionality to navigate in pages with arrow keys

apps/web/app/pdf/[...pdfId]/page.tsx, apps/web/app/tracks/[...trackIds]/page.tsx, apps/web/components/Print.tsx, apps/web/screens/Landing.tsx, packages/db/package.json, packages/db/prisma/migrations/20240402163133_init/migration.sql, packages/db/prisma/schema.prisma, packages/db/prisma/tsconfig.json, packages/ui/src/Blog.tsx, packages/ui/src/BlogAppbar.tsx, packages/ui/src/CodeProblemRenderer.tsx, packages/ui/src/LessonView.tsx, packages/ui/src/ProblemAppbar.tsx, packages/ui/src/TrackCard.tsx
Fixes #113 
- added backend endpoints to nextjs so we can get rid of all the firebase calls
@hkirat haven't changes to admin part, will do that when integrating auth.
=> added db calls from postgres in nextjs app

packages/ui/src/BlogAppbar.tsx, packages/ui/src/PageToggle.tsx
=> fixed slides dropdown

apps/web/app/tracks/[...trackIds]/page.tsx, apps/web/screens/Landing.tsx, package-lock.json, packages/db/prisma/migrations/20240403154304_added_mcq/migration.sql, packages/db/prisma/schema.prisma, packages/store/src/atoms/tracks.ts, packages/ui/src/BlogAppbar.tsx, packages/ui/src/LessonView.tsx, packages/ui/src/MCQQuestion.tsx, packages/ui/src/MCQQuestionCard.tsx, packages/ui/src/MCQQuestionRenderer.tsx
feat: Added #73 
haven't created submissions as there is no auth 
https://github.com/code100x/daily-code/assets/136337515/46b4a690-0178-45bb-b6a5-0c39650bd5c7
=> feat: Added MCQ

packages/db/prisma/migrate.ts
Fixes #134 
- Re-using ids from firestore in postgres, changed migrate script
- Tested on local it's working fine
=> added id in db migrate script

apps/web/components/AppbarClient.tsx, apps/web/screens/Landing.tsx, packages/ui/package.json, packages/ui/src/Appbar.tsx, packages/ui/src/SearchDialog.tsx, packages/ui/src/TrackList.tsx, packages/ui/src/index.tsx, packages/ui/src/shad/ui/dailog.tsx, yarn.lock
This pull request adds the functionality of searching tracks 
https://github.com/code100x/daily-code/assets/66407522/a7e2ee59-2777-4dc8-abb8-8bcb6aec69fa
=> Feat: Searching Tracks become easy

apps/web/components/RedirectToLastSolved.tsx
Skipped the route without problem id in router to facilitate going back to home page.
Addresses https://github.com/code100x/daily-code/issues/41
=> chore: skip route without probId in router

apps/web/components/utils.tsx, apps/web/screens/Landing.tsx, packages/db/prisma/migrations/20240408080322_added_categories/migration.sql, packages/db/prisma/schema.prisma, packages/store/src/atoms/filter.ts, packages/store/src/atoms/index.ts, packages/ui/src/Categories.tsx, packages/ui/src/TrackCard.tsx, packages/ui/src/Tracks.tsx, packages/ui/src/index.tsx
Fixed #89 
- merged conflicts #126 
- instead of hardcoding categories fetching unique categories from db
https://github.com/code100x/daily-code/assets/136337515/49fbdd97-a49e-44ee-b4db-0725efc87394
=> feat: Added Categories

packages/ui/src/BlogAppbar.tsx
=> remove bug in appbar keypress

packages/db/prisma/seed.ts
Description:
This pull request resolves a TypeScript compilation error encountered while running the seed script. The error occurred due to missing properties in the seed data object passed to Prisma.
Changes:
Added missing sortingOrder property to the seed data object to align with the requirements of the TrackProblems model in Prisma.
Details:
Updated the prisma/seed.ts file to include the sortingOrder property in the seed data object.
Verified that the TypeScript compilation error is resolved and the seed script runs successfully.
before - 
after -
=> Fix TypeScript compilation error in seed script

packages/db/prisma/seed.ts, packages/db/prisma/seedsData.ts, packages/ui/src/Tracks.tsx
Fixed the overflow of the wrapper link tag
=> [Fix] Issue #165 and Updated seed.ts

packages/ui/src/SearchDialog.tsx
- Enhancements to SearchDialog for Keyboard Navigation
- The modifications allow users to navigate through search results using the up and down arrow keys and to select a search result using the Enter key.
https://github.com/code100x/daily-code/assets/22127725/bead361d-d35d-4cf9-abdc-c3a09608cd2e
=> feat: Added Keyboard Navigation and selection in SearchDialog component

packages/ui/src/Categories.tsx
fixes: #204
added select tag and can now add more categories in the future when required
https://github.com/code100x/daily-code/assets/136328410/d6141f2a-ef5b-4d3d-b442-25d205d1d8b5
=> Changed category Button To Select

packages/ui/app/CodeBlock.module.css, packages/ui/package.json, packages/ui/src/CodeBlock.tsx, packages/ui/src/NotionRenderer.tsx
This PR fixes issue no https://github.com/code100x/daily-code/issues/106
Copy button glides along when scrolling, it should remain fixed
=> Fixes bug #106

packages/ui/src/Tracks.tsx
Before fixing the ui we are able to click outside the div
https://github.com/code100x/daily-code/assets/123832227/54bf6450-c4b9-47f9-8c14-99d5b737349a
after fixing the ui we are not able to click outside the div
https://github.com/code100x/daily-code/assets/123832227/d2bae8b0-f2d6-4ce6-b2d8-a77a5a1dba6a
=> List item taking excess width than required (higher screen res) 

apps/web/app/admin/page.tsx, apps/web/app/api/createTrack/route.ts, packages/ui/src/TracksEditor.tsx
> **Problem:** #176 
Manual addtion of the Notion to the Database 
> **Solution:**
Created a api endpoint to hit it from the admin pannel 
> **How It works?**
This API end point takes NotionLink, ImageLink with the description and seeds the tracks into the database. By fetching track data from the Notion API
**Implementation:**
```
1. Fetch the Title and id of the Notion document within the link itself
2. Fetch the page with the id and fetch all of the data in the block with the ids with the NotionAPI Client
3. Propogate the data to the database
```
https://github.com/code100x/daily-code/assets/108384868/74d38a28-67d4-481b-9fc0-32dc505fdf39
=> [Urgent Feature]: #176 Added createTrack route

packages/ui/src/PageToggle.tsx, packages/ui/src/TrackCard.tsx
-fixes key in pageToggle
Resolves #245
=> [fixes]:Pagetoggle key #245

apps/web/components/Providers.tsx, packages/ui/package.json, yarn.lock
- 1 Fixed Toaster Configuration
=> Fixed Toaster Configuration 

packages/ui/src/BlogAppbar.tsx
This PR adds a sticky app bar to the project with hide/show behavior on scroll. The app bar remains visible when scrolling up and hides when scrolling down.
Video Attached : 
https://github.com/code100x/daily-code/assets/101008478/9ac18bb1-51f0-4807-9a33-9578ddea1061
=> Implement hide/show behavior on scroll in Blog Appbar

packages/ui/src/CompleteTrackCard.tsx
=> Fixed: CompleteTrack

apps/web/app/pdf/[...pdfId]/page.tsx, apps/web/app/tracks/[...trackIds]/page.tsx, apps/web/components/AddTestCase.tsx, packages/ui/src/CodeBlock.tsx, packages/ui/src/ErrorBoundary.tsx, packages/ui/src/LinkCard.tsx
removes ts-ignores and added types
=> Fix/removes type errors and ts-ignores

apps/web/app/layout.tsx, package.json
- Implemented a top bar loader using [this](https://www.npmjs.com/package/nextjs-toploader) library
https://github.com/code100x/daily-code/assets/22127725/10175feb-cc7b-4932-86eb-7e81967a3e14
Resolves #302
=> feat: Added top bar loader

packages/ui/src/Categories.tsx
- light mode category not visible properly
-  #303 
Resolves #[Issue Number if there]
=> light mode category not visible

apps/web/app/profile/layout.tsx, apps/web/app/profile/page.tsx, apps/web/app/profile/submissions/page.tsx, apps/web/components/ProblemSubmissionTable.tsx, apps/web/components/ProfileChildren.tsx, apps/web/components/ProfileSidebar.tsx, apps/web/components/UserDetailForm.tsx, packages/store/src/atoms/profileSidebar.ts, packages/ui/src/Appbar.tsx, packages/ui/src/BlogAppbar.tsx, packages/ui/src/UserAccountDropDown.tsx, packages/ui/src/UserImage.tsx, packages/ui/src/code/CodeSubmitButton.tsx, packages/ui/src/profile/ProfileOptions.tsx, packages/ui/src/shad/ui/dropdown-menu.tsx
- 1 Added User Drop Down and profile page 
You can check below the changes : 
https://github.com/code100x/daily-code/assets/118182376/0d27241c-bead-4025-ab33-615b73261a70
- 2 Resolved the issue of error in submitting the code , as the problemStatementId was hardcoded so whenever we try to submit the problem statement other than problemStatementId = 1 then it doesn't get submitted , so this PR fixes the same 
Before : 
After : 
Resolves #242
=> Added the User Drop Down and also added the profile page

packages/ui/src/SearchDialog.tsx
=> added track track not found

.gitignore, README.md, packages/db/docker-compose.yml, packages/db/setupDB.sh
=> Automate DB Setup in a single script

apps/web/app/profile/layout.tsx, apps/web/app/profile/page.tsx, apps/web/components/AddProblemStatementForm.tsx, apps/web/components/ProblemSubmissionTable.tsx, apps/web/components/Signin.tsx, apps/web/components/UserDetailForm.tsx, packages/ui/src/Appbar.tsx, packages/ui/src/UserAccountDropDown.tsx, packages/ui/src/UserImage.tsx, packages/ui/src/profile/ProfileOptions.tsx, turbo.json
- #373 
Changes Made:
- fixed lint warnings
- fixed build failed issue
- fixed google user icon 403 Forbidden error
- added keys to some components
=> Fixed: Build Issues

apps/web/components/AddProblemStatementForm.tsx, apps/web/components/AddTestCase.tsx, apps/web/components/LessonView.tsx, apps/web/components/ProfileChildren.tsx, apps/web/components/ProfileSidebar.tsx, apps/web/components/UserDetailForm.tsx, packages/store/src/atoms/index.ts, packages/ui/package.json, packages/ui/src/SearchDialog.tsx
- 1 #362 
- 2 #351 
Resolves #362  
Before/After:
1.
2.
=> Fixed issue 362

README.md
=> fix: fixes #380

apps/web/screens/Landing.tsx
- 1 Make the footer sticky to always stick to the bottom
Resolves #[Issue Number if there]
#330
=> fixed footer to always stick to the bottom

packages/ui/src/PageToggle.tsx
=> Disabled the dropdown when you were on that slide.

.github/workflows/lint_commit.yml
- 1 YAML file check for conventional commit message then performs the linting and formating
Resolves #14
=> Adding the CI/CD pipeline

.dockerignore, Dockerfile, README.md, docker-compose.yml, package.json
I've successfully integrated Bind mounts  with docker-compose file. when running 'docker compose watch', if we change any file and save it, the docker image is hot-reloaded.
@hkirat  please review and notify me if any change is needed.
=> docker integration with bind mounts

apps/web/screens/footer.tsx
- Added GitHub link and updated other links in footer
=> updated footer links

apps/web/components/LessonView.tsx
1. Disable the login requirement during the development phase on the LessonView pages
Resolves #437
=> Fixed: Disable Login Requirement on `LessonView`

apps/web/components/RedirectToLoginCard.tsx
**Fixed UI**
on Mobile
FYI my screen is too big that's what it appears so small but will work properly on average desktop and laptop screen sizes
=> fix redirectToLoginCard UI

apps/web/components/CodeBlock.tsx
- 1 The copy button hide the code.
- 2 After click on copy the copied take alot of space.
Resolves #425
=> Fixed copy button

apps/web/components/TrackPreview.tsx
Before
Updated ui Design and showing Logic
=> Track Preview Ui fix and logic update

apps/web/components/Categories.tsx
- Created a category for all which can go back to all categories in mobile view and desktop. 
Resolves #479
=> fixes 479 added all category item

apps/web/.env.example, apps/web/components/utils.tsx, apps/web/lib/cache/cache.ts, apps/web/lib/cache/in-memory-cache.ts, apps/web/lib/cache/redis-cache.ts, package.json, packages/db/.env.example, packages/db/Cache.ts
Resolves #490  
- [ yes ] I have made by code review.
- [ yes ] I assure there is no similar/duplicate pull request regarding same issue
=> Added the cache for the getproblem function

apps/web/components/CodeBlock.tsx
- 1 The position of copy button image is corrected 
Resolves #482 
- [ yes ] I have performed a self-review of my code
- [ yes ] I assure there is no similar/duplicate pull request regarding same issue
=> position of copy_button_image corrected

apps/web/components/ScrollToTopWrapper.tsx
-  Made "Go to Top" Button Theme Responsive and Improved its styling
Resolves #514
Overridded the styles of the "Go to top" button and used the resolvedTheme value from the useTheme hook to determine the color of the SVG used in the "Go to top" button.
Before:
After:
=> made scroll to top button theme responsive

apps/web/components/ModeToggle.tsx
A simple toggle button instead of a drop down menu.
=> Update ModeToggle.tsx  

packages/db/prisma/seed.ts
- Resolve unique constraint violation when seeding tracks
- Ensure tracks with duplicate IDs are not created during the seeding process
Resolves #[476] 
- [✓] I have performed a self-review of my code
- [✓] I assure there is no similar/duplicate pull request regarding same issue
=> fix(db): Resolve unique constraint violation when seeding tracks issue #476

apps/web/components/SearchDialog.tsx
#457
**Added voice search feature to the search bar**
https://github.com/code100x/daily-code/assets/88326960/796cf10a-d614-4f50-9661-6cd78e1066aa
=> voice-search

apps/web/components/ModeToggle.tsx
=> fix: button import

apps/web/components/CodeBlock.module.css
- 1 Wraps the code components responsively
- 2 Works for sm screens now.
Resolves #502 
###Before fix:
###After fix:
=> fix: content wrap for Code block

apps/web/components/TrackPreview.tsx
- Resolved the width issue of the Track Preview Card
Resolves #520
**Screenshots**
Before:
After:
=> track preview width resolved

apps/web/components/CodeBlock.tsx, yarn.lock
1- Fixed the issue where the copy button was not visible until the user scrolls horizontally and moved as the user scrolled.
2 - Ensured that the copy button remains in its fixed position (top right corner) even when the content is scrolled.
Resolves #528 
- I have performed a self-review of my code
- I assure you there is no similar/duplicate pull request regarding the same issue
=> Bug Fix: Copy button fixed at the Top right of Code Block and visible even without scrolling 

apps/web/app/pdf/[...pdfId]/page.tsx, apps/web/components/Signin.tsx
- Update signIn component for redirect url from searchparams
- Update /pdf endpoint to verify if user is logged in or not 
Resolves #562
=> Issue: 562 fix: download pdf after login

apps/web/components/Categories.tsx
=> Fixed Border-radius problem in navbar #542

apps/web/components/TrackTools.tsx
Added a back to home button where user can redirect to home page.
Resolves #591
=> feat(button): added back to home button

apps/web/components/ContentSearch.tsx, apps/web/components/Hero.tsx, apps/web/components/Tracks.tsx, apps/web/screens/Landing.tsx, package.json
- 1 added fuse.js for search-bar
Resolves #576 
https://github.com/user-attachments/assets/dc8c57ed-41ba-4b46-bc99-16accd38a145
=> added-fuse.js

apps/web/app/admin/layout.tsx, apps/web/components/Tracks.tsx, apps/web/components/admin/EditTrackCard.tsx, apps/web/components/utils.tsx, apps/web/screens/Admin.tsx
- Admin would be able to change the cohort for any uploaded track.
@hkirat @devsargam 
Resolves #604 
https://github.com/user-attachments/assets/c492396b-3ba3-4501-a610-44ac521a62e8
=> feat-604: Added input to change cohort in Admin Panel

apps/web/app/canva-track/[...trackIds]/page.tsx, apps/web/components/TrackCard-2.tsx, apps/web/components/admin/AddTrackCard.tsx, apps/web/components/admin/EditTrackCard.tsx, apps/web/components/utils.tsx, packages/db/prisma/migrations/20241101231656_add_canva/migration.sql, packages/db/prisma/schema.prisma
=> feat: add canva embed and route

apps/web/components/ContentSearch.tsx
1 Fix unresponsive height behavior
2 Increased Search Bar height
3 Added 'Track' prefix in front of track title for more descriptive information
Resolves #698
=> Fix unresponsive image height and increased search bar height

Dockerfile.prod
- Specify prisma version inside of docker
- Install openssl lib for alpine
=> fix: prisma version issue inside of docker
