packages/ui/src/pages/Signup.tsx
This pull request resolves issue #20 .
- Previously, importing SVG resulted in an [object object] when used inside the image source. 
- Modified the code to use `GithubIcon.src` instead, resolving the issue.
- - Modified the code to use `GoogleIcon.src` instead, resolving the issue.
- Utilized the `shadcn` button component to render the button text.
=> fix #20: Render SVG icons and text in Signin

packages/ui/src/NotionRenderer.tsx
Removed the Header and Title Displayed on the Notion Page Renderer.
Fixes #34
=> Removed the Header and Title in Notion Rendered

apps/web/app/layout.tsx, packages/ui/src/BlogAppbar.tsx, packages/ui/src/NotionRenderer.tsx
This pull request resolves issue #44 .
- Previously, the NotionRenderer utilized the `theme` property from the **useTheme** hook, which did not account for the system theme. I have modified it to use `resolvedTheme` property to dynamically provide dark and light themes based on the system theme.
- Adjusted property casing in SVG elements from kebab-case to camelCase (e.g., stroke-width to strokeWidth), aligning with best practices.
- Addressed a hydration error in the next-themes client component, which was causing issues by setting properties on HTML attributes. To mitigate this, I have implemented the use of suppressHydrationWarning to prevent this error. This issue was particularly noticeable in conjunction with the app router.
=> Fix #44: Add system theme to notion

packages/ui/src/BlogAppbar.tsx
This Pull request is raised in reference to improvement requested #60  
In the first and last pages of a track the prev and next button are greyed out respectively. Along with that the mouse pointer type is changed to **not-allowed** instead of a clickable option.
=> Improvement to the prev and next buttons for BlogAppbar

apps/web/app/layout.tsx, packages/ui/src/NotionRenderer.tsx
This pull request removes css fetch call every time a new track is load
https://github.com/code100x/daily-code/assets/66407522/c2384036-34cb-404f-a188-560d4b60a555
https://github.com/code100x/daily-code/assets/66407522/87c720a6-617f-49d7-b60a-6b19e460b6e2
The notionRenderer is a client component which had the css imports So whenever prev or next button are pressed with the js css also got requested from server which is unnecessary, So I moved it up to the layout.tsx where it fetches only once and stays for all the pages
This reduces the number of call from 4 to 3 and also supports next caching
=> Fix: Requesting notion css on every slide's tracks

packages/db/prisma/seed.ts
closes #201
In the original version of the `seed.ts` file, the script was creating records in the `categories` and `trackCategory` table before it had finished creating records in the `track` table. Because there are dependencies between these tables, this was causing issues with the seeding process.
To resolve this issue, I modified the script to wait for all promises related to the `track` table to resolve before proceeding to create records in the `categories` table. I did this by adding an `await Promise.all(promises)` line after the `forEach` loop that creates the `track` records.
This ensures that all `track` records are created before we start creating `categories` records, which prevents the foreign key constraint errors we were seeing previously.
=> Fix :  Seeding data to track table before categories and trackCategory  table

packages/ui/src/shad/ui/card.tsx
fixes: #211
the error doesn't show now and was caused because of a `<p>` tag which was located in "daily-code/packages/ui/src/shad/ui/card.tsx"
this happens because We use components to build the React-based websites, These components are made using HTML tags. It is very important not to nest the same HTML elements.
=> fix: Hydration failed error

README.md, packages/ui/src/TrackCard.tsx
This is a readme.md change which adds the yarn alternative commands for migrating, seeding via prisma. 
This addresses the issue #196 which I faced while setting it up on my windows machine. 
The issue might have occurred due some incompatibility of yarn workspaces using npx.
=> Addresses issues #196 & #210

apps/web/app/tracks/[...trackIds]/page.tsx, apps/web/components/RedirectToLastSolved.tsx
[dailycode_track_fix.webm](https://github.com/code100x/daily-code/assets/45840495/157cb223-63fa-4e2e-ba6f-813dc23da725)
- 1 if user visits `/tracks/<track>/<problem>` where track or problem is invalid we will properly show the 404 error page (in prod nothing was done just a blank page was shown)
- 2 if user visits `/tracks/<track>` we correctly resolve and redirect to `/tracks/<track>/<problem>` (in prod we didnt resolve the promise and hence redirected to `/tracks/<track>/[object%20Promise]`)
Resolves #278
=> fix /tracks related routing bug

packages/ui/src/Categories.tsx
- 1 Makes the categories buttons on the category-filter-bar Capsule shape
Resolves #306
=> fix: Makes categories btn capsule-shaped

apps/web/app/layout.tsx
**Dailycode** is used in title whereas **DailyCode** is used in navbar.
PR to fix inconsistent use of cases adhering to high code quality standards. 
- Following uniform standards all across
=> update to TitleCase : Dailycode -> DailyCode

packages/ui/src/BlogAppbar.tsx, packages/ui/src/PageToggle.tsx
- 1 Make navbar more responsive for smaller screen for better readability 
Resolves #178 
-PR #182 created by me has same changes but now it has merge conflicts so creating this new and removing that
- Before
- After
**Change navbar title from page title to track title**
1. As the page title is visible below the navbar title
2. After some time when we continue we forgot that what track we are at 
- Before
- Now
=> Make navbar of pages more responsive for smaller screen

packages/ui/src/CodeBlock.tsx
@hkirat The previous pull request (#289 ) was closed because that has some yarn.lock conflict.
- This pr fixes the codeblock overflowing issue.
- In this I have implemented CSS adjustments to ensure code blocks are properly contained within the viewport on mobile devices.
Resolves #288
=> Fix mobile screen code block overflow issue

packages/ui/app/CodeBlock.module.css, packages/ui/src/CodeBlock.tsx
- 1 The "copied" popup was not coming up consistently, made a state variable and did conditional rendering for the popup
Before 
After
=> Fixed the "Copied!!" popup when copying the code

packages/db/setupDB.sh
- 1 fixed : error occurred when running setupDB.sh. 
below is the error screenshot.  error is solved when replaced 'docker compose' to 'docker-compose' in setupDB.sh
Resolves #[Issue Number if there]
=> replaced 'docker compose' to 'docker-compose' in setupDB.sh

packages/ui/src/Tracks.tsx
- Adds a dropdown just below the category filter bar/dropdown.
- Sorting is based on _alphabetically ascending & descending, newest first, oldest first orders._
- Improves navigation.
- Fix typos in function name from `fitlreTracks` to `filterTracks` removed an **"e"** 
**List closed:**
**List opened:**
Resolves #385 #178 #58
=> Adds tracks sorting for better navigation

packages/db/setupDB.sh
- 1 In the initial DB setup, when we ask for db's username, the script prompts `Enter your db password: ` which creates confusion and error while setting up. Updated that to `Enter your db username: `
=> updated inital DB setup setupDB.sh

apps/web/components/TrackCard.tsx, apps/web/components/TrackPreview.tsx, apps/web/components/Tracks.tsx
- **Added tracks preview feature** 
- View the complete description.
- Check all the contents of that particular track on the home page instead of going to track's page.
- Navigate directly to a particular track chapter or start from the beginning.
- **Fixed few minor bugs**
- Fixed the description length in the track card to make the card size uniform.
- In the case of multiple categories for a track, the categories would be on top of one another. Fixed it with cleaner by | separating it (e.g. Web Development | Projects).
https://github.com/code100x/daily-code/assets/86565216/7824f037-ea8d-4084-aadc-a50f52cfeff8
=> feat: added track preview & fixed small bugs

apps/web/components/SearchDialog.tsx
- 1 Ensure the dialog opens with Cmd+K on macOS and Ctrl+K on Windows.
This change checks for both metaKey and ctrlKey to provide cross-platform
support. Additionally, the keypress handler has been optimized for better
readability and maintainability. Mac users press Cmd+K only to open a search.
Resolves #[#421]
=> Fix : keypress handler for Cmd+K on macOS and Ctrl+K on Windows

apps/web/app/tracks/[...trackIds]/page.tsx, apps/web/components/ScrollToTopWrapper.tsx, apps/web/package.json, yarn.lock
1. Adds a "Go to Top" button on every learning track page.
2. Enhances user navigation experience by allowing users to quickly return to the top of the page.
Resolves  [#451]
This PR introduces a "Go to Top" button on every learning track page within the DailyCode platform. This feature enhances the user experience by providing a convenient way for users to quickly return to the top of the page.
Added a `ScrollToTopWrapper` component using the `react-scroll-to-top` library.
Wrapped the track pages with the ScrollToTopWrapper component to enable the "Go to Top" functionality.
=> [Feature] Add "Go to Top" Button on Every Learning Track Page

apps/web/components/Blog.tsx, apps/web/components/BlogAppbar.tsx, apps/web/components/Pagination.tsx, apps/web/components/Tracks.tsx
When clicking on an item, the select value changes so quickly that the popper disappears and the touch event simultaneously clicks the element behind it
- 1 Bug 459
- 2
Resolves #[Issue Number if there] 
#459
=> Fixed stopPropogation issue on mobile devices

apps/web/components/CodeBlock.tsx
- 1 Made the copy button's positioning better
Resolves #[[482](https://github.com/code100x/daily-code/issues/482#issue-2381541640)] 
- the copy icon looks even bad in smaller code blocks
=> Fixed: copy button positioning

apps/web/components/ModeToggle.tsx, apps/web/components/Tracks.tsx, apps/web/components/admin/CompleteAddTracks.tsx, apps/web/components/admin/CompleteTrackCard.tsx, apps/web/components/admin/EditCategories.tsx, apps/web/components/utils.tsx, apps/web/screens/Admin.tsx, packages/db/prisma/migrations/20240803144221_added_cohort/migration.sql, packages/db/prisma/schema.prisma, packages/ui/package.json, packages/ui/src/index.ts, packages/ui/src/shad/ui/switch.tsx, yarn.lock
https://github.com/user-attachments/assets/4003b439-284e-47fc-97d7-80da71eda291
=> added section for Cohort 3

apps/web/app/pdf/[...pdfId]/page.tsx, apps/web/app/tracks/[...trackIds]/page.tsx, apps/web/components/Blog.tsx, apps/web/components/LessonView.tsx, apps/web/components/PageToggle.tsx, apps/web/components/Print.tsx, package.json, yarn.lock
- 1 Makes the PDF page breaks consistent 
- 2 The Images in the generated PDF are well visible
- 3 The pagination bar in excluded in the generated pdf.
Resolves #494 
- 1 Some of the images were getting hidden by the new blog-component
- 2 The pagination was coming include in the pdf
- 1 The Page breaks were made consistent and Images were visible.
- 2 The Pagination Component was excluded in the pdf
=> fixed the download-pdf option issue

apps/web/components/Categories.tsx, apps/web/tailwind.config.js
- 1) overflow of categories tab
Resolves overflow of categories:
The dropdown used to appear at 1280px i changed it to around 1730px where the overflow of text begins, we can adjust it according to our use, i have defined a custom screen width in talwind config file
=> fixed overflow of categories

apps/web/app/globals.css, apps/web/components/Blog.tsx, apps/web/components/CodeBlock.module.css, apps/web/components/CodeBlock.tsx, apps/web/components/NotionRenderer.tsx, apps/web/components/mcq/MCQPanel.tsx, apps/web/tailwind.config.js
-  Heading  
-  Notion text and list
-  Text block
-  Background
Resolves #549 
@hkirat Hey does this looks fine?
@devsargam
=> Feat  custom renderers (Heading, textblock etc)

.prettierrc, apps/web/app/pdf/[...pdfId]/page.tsx, apps/web/app/tracks/[...trackIds]/page.tsx, apps/web/components/Blog.tsx, apps/web/components/BlogAppbar.tsx, apps/web/components/CustomPagination.tsx, apps/web/components/LessonView.tsx, apps/web/components/ModeToggle.tsx, apps/web/components/NotionRenderer.tsx, apps/web/components/PageToggle.tsx, apps/web/components/TrackTools.tsx, apps/web/package.json, apps/web/tailwind.config.js, packages/store/src/atoms/index.ts, packages/store/src/atoms/view.ts, yarn.lock
- Added a legacy mode button to toggle between the new and the old UI on the Blog page.
- Fixed and improved the legacy UI a lil which was required (eg. header)
- Improved Mobile and Tablet view.
- Added pretier-tailwind for sorting the tailwind classes better.
Resolves #602  
@devsargam @hkirat 
https://github.com/user-attachments/assets/b011a63b-9f03-47a4-a436-7866564a3113
=> feat-602: Added leagacy mode button on Blog Page

apps/web/components/Tracks.tsx
UX: Default cursor on pagination button hover to pointer cursor 
Resolves #654
- [ ✔ ] I have performed a self-review of my code
- [ ✔] I assure there is no similar/duplicate pull request regarding same issue
=> fix: add pointer cursor on hover for pagination buttons in tracks

apps/web/components/UserAccountDropDown.tsx
- Updated user dropdown menu design to align with the current UI.
- Improved component structure and styling for better user experience.
- [✅](https://emojipedia.org/check-mark-button) I have performed a self-review of my code.
- [✅](https://emojipedia.org/check-mark-button) I assure there is no similar/duplicate pull request regarding the same issue.
- [✅](https://emojipedia.org/check-mark-button) Updated the user dropdown menu to make it more familiar with the current UI.
**Before:**
**After:**
=> Enhance User Dropdown Menu UI and Improve Component Structure

apps/web/app/api/AddTracks/route.ts, apps/web/components/Hero.tsx, apps/web/components/Tracks.tsx, apps/web/components/admin/CompleteTrackCard.tsx, apps/web/tailwind.config.js
- admin not being able to add tracks**
- filter for cohort selection**
=> fix: all the current blocking issues

Dockerfile.prod, apps/web/next.config.js, apps/web/package.json, docker-compose.yml
=> feat: add multistage Dockerfile for reduced image size.
